CREATE TABLE supplier(
  SNO TEXT PRIMARY KEY,
  SNAME TEXT,
  STATUS INTEGER,
  CITY TEXT
);

INSERT INTO supplier (SNO,SNAME,STATUS,CITY)VALUES
  ('S1', 'SMITH', 28, 'MANCHESTER'),
  ('S2', 'JOHN', 7, 'MANCHESTER'),
  ('S3', 'SANTINO ESCOBAR', 33, 'MADRID'),
  ('S4', 'PABLO', 5, 'BARCELONA');

SELECT * FROM supplier;